#!/bin/bash

# Define initial states
last_state=""

# Function to toggle OBS camera
toggle_camera() {
  if [[ "$1" -eq 1 ]]; then
    php ~/anyhow/obs/scripts/camera/toggle 1
  else
    php ~/anyhow/obs/scripts/camera/toggle 0
  fi
}

# Ensure jq is installed
if ! command -v jq &> /dev/null; then
  echo "Error: jq is required but not installed. Install jq and rerun the script."
  exit 1
fi

# TODO: validate if OBS is opened

# Subscribe to i3 window events and monitor for fullscreen mode changes
i3-msg -t subscribe -m '[ "window" ]' | while read -r event; do
  echo $event | jq 
  fullscreen_mode=$(echo "$event" | jq -r '.container.fullscreen_mode')
 output=$(echo "$event" | jq -r '.container.output')

  # Only proceed if it's a fullscreen_mode change event on DisplayPort-0
  if [[ "$output" == "DP-0" ]]; then
    # Update current state based on fullscreen mode value
    current_state=$fullscreen_mode

    # Only proceed if there is a change in fullscreen state
    if [[ "$current_state" != "$last_state" ]]; then
      echo "Fullscreen mode on DP-0: $current_state"
      last_state=$current_state
      toggle_camera $current_state
    fi
  fi
done
